### ISSUE TITLE
Base64 encoding on byte slices

### ISSUE THREAD

**Issue by iancboswell** [TheOnlyRew/null#1]
Need to figure out behavior with MarshalText, UnmarshalText, Scanner, and Valuer regarding base64 encoding. This will then inform how we implement those functions in ByteSlice. MarshalJSON automatically base64 encodes the byte slice.

**Comment by TheOnlyRew** [comment]
This has been answered as part of #2.

The gist is that passing a byte slice to `json.Marshal()` will result in a base64-encoded string being generated and returned. My understanding is that this is to prevent sending non-utf8 (more accurately, non-ASCII) across an application/json interface. This strikes me as a good idea, and one that we should take to heart when considering SQL queries and textual encodings.
